theme: jekyll-theme-dinky
baseurl: /
repository: zemkat/grima
destination: dist
exclude: [
  "*.log",
  "*.phar",
  "*.sql",
  "*.swp",
  "*.tgz",
  "*.zip",
  ".bundle",
  ".htaccess",
  "CreatePhar.php",
  "Doxyfile",
  "Gemfile",
  "Gemfile.lock",
  "Makefile",
  "broken-toys",
  "config",
  "dist/",
  "docker/",
  "docs/samples",
  "node_modules",
  "package.json",
  "package-lock.json",
  "fix_urls.js",
  "releases",
]
